#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::collections::BTreeMap;
use std::error::Error;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use schemars::schema::RootSchema;
use serde_json::{Map, Value, json};
use typify::{TypeSpace, TypeSpaceSettings};

const GENERATED_HEADER: &str = "\
// @generated by wolf-api-gen from openapi/wolf.openapi.json — do not edit.
// Regenerate with: cargo run -p wolf-api-gen
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]
#![allow(missing_docs)]

";
const SCHEMA_REF_PREFIX: &str = "#/components/schemas/";
const DEFINITION_REF_PREFIX: &str = "#/definitions/";
const RUNNER_DEFINITION: &str = "Runner";
const APP_CMD_DEFINITION: &str = "AppCMD";
const APP_DOCKER_DEFINITION: &str = "AppDocker";

type Result<T> = std::result::Result<T, Box<dyn Error>>;

fn main() -> Result<()> {
    let paths = Paths::from_manifest_dir()?;
    let generated = generate_types(&paths.schema)?;
    let current = fs::read_to_string(&paths.types).ok();

    if current.as_deref() == Some(&generated) {
        println!("{} is already up to date", paths.types.display());
        return Ok(());
    }

    fs::write(&paths.types, generated)?;
    println!("generated {}", paths.types.display());
    Ok(())
}

struct Paths {
    schema: PathBuf,
    types: PathBuf,
}

impl Paths {
    fn from_manifest_dir() -> Result<Self> {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let crates_dir = manifest_dir.parent().ok_or_else(|| {
            invalid_data("wolf-api-gen must be inside the workspace crates directory")
        })?;
        let wolf_api = crates_dir.join("wolf-api");

        Ok(Self {
            schema: wolf_api.join("openapi/wolf.openapi.json"),
            types: wolf_api.join("src/types.rs"),
        })
    }
}

fn generate_types(schema_path: &Path) -> Result<String> {
    let source = fs::read_to_string(schema_path)?;
    let spec: Value = serde_json::from_str(&source)?;
    let normalized = normalize_spec(spec)?;
    let root: RootSchema = serde_json::from_value(normalized)?;

    let mut settings = TypeSpaceSettings::default();
    settings.with_derive("PartialEq".to_string());

    let mut type_space = TypeSpace::new(&settings);
    type_space.add_root_schema(root)?;

    let formatted = format_generated(&type_space.to_stream().to_string())?;
    Ok(format!("{GENERATED_HEADER}{formatted}"))
}

fn format_generated(source: &str) -> Result<String> {
    match rustfmt_wrapper::rustfmt(source) {
        Ok(formatted) => Ok(formatted),
        Err(rustfmt_wrapper::Error::NoRustfmt) => rustfmt_from_path(source),
        Err(error) => Err(error.into()),
    }
}

fn rustfmt_from_path(source: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2018", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;
    let mut stdin = child
        .stdin
        .take()
        .ok_or_else(|| invalid_data("failed to open rustfmt stdin"))?;
    stdin.write_all(source.as_bytes())?;
    drop(stdin);

    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err(invalid_data(format!(
            "rustfmt failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ))
        .into());
    }

    Ok(String::from_utf8(output.stdout)?)
}

fn normalize_spec(mut spec: Value) -> Result<Value> {
    let schemas = spec
        .pointer_mut("/components/schemas")
        .and_then(Value::as_object_mut)
        .ok_or_else(|| invalid_data("OpenAPI document has no components.schemas object"))?;
    let schemas = std::mem::take(schemas);
    let renames = schema_renames(&schemas)?;
    let mut definitions = Map::new();

    for (old_name, mut schema) in schemas {
        rewrite_schema(&mut schema, &renames)?;
        let new_name = renames
            .get(&old_name)
            .ok_or_else(|| invalid_data(format!("missing rename for schema {old_name}")))?;
        definitions.insert(new_name.clone(), schema);
    }

    let reference_definitions = definitions.clone();
    for schema in definitions.values_mut() {
        normalize_unions(schema, &reference_definitions)?;
    }

    validate_runner_definition(&definitions, APP_CMD_DEFINITION, "process")?;
    validate_runner_definition(&definitions, APP_DOCKER_DEFINITION, "docker")?;
    if definitions.contains_key(RUNNER_DEFINITION) {
        return Err(invalid_data("the Wolf schema already defines Runner").into());
    }

    let mut hoisted_runner_count = 0;
    for schema in definitions.values_mut() {
        hoist_runner_union(schema, &mut hoisted_runner_count);
    }
    if hoisted_runner_count == 0 {
        return Err(invalid_data("the Wolf schema contains no recognized runner union").into());
    }

    definitions.insert(
        RUNNER_DEFINITION.to_string(),
        json!({
            "oneOf": [
                {"$ref": definition_ref(APP_CMD_DEFINITION)},
                {"$ref": definition_ref(APP_DOCKER_DEFINITION)}
            ]
        }),
    );

    Ok(json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "WolfApiTypes",
        "type": "object",
        "definitions": definitions
    }))
}

fn schema_renames(schemas: &Map<String, Value>) -> Result<BTreeMap<String, String>> {
    let mut old_to_new = BTreeMap::new();
    let mut new_to_old = BTreeMap::new();

    for old_name in schemas.keys() {
        let new_name = normalized_schema_name(old_name)?;
        if let Some(previous) = new_to_old.insert(new_name.clone(), old_name.clone()) {
            return Err(invalid_data(format!(
                "schema names {previous} and {old_name} both normalize to {new_name}"
            ))
            .into());
        }
        old_to_new.insert(old_name.clone(), new_name);
    }

    Ok(old_to_new)
}

fn normalized_schema_name(name: &str) -> Result<String> {
    let reflected = match (
        name.strip_prefix("rfl__Reflector_"),
        name.strip_suffix("___ReflType"),
    ) {
        (Some(without_prefix), Some(_)) => without_prefix
            .strip_suffix("___ReflType")
            .ok_or_else(|| invalid_data(format!("invalid reflected schema name {name}")))?,
        _ => name,
    };
    let untagged = reflected.strip_suffix("__tagged").unwrap_or(reflected);
    let normalized = untagged.rsplit("__").next().unwrap_or_default();

    if normalized.is_empty() {
        return Err(invalid_data(format!("schema name {name} normalizes to an empty name")).into());
    }

    Ok(normalized.to_string())
}

fn rewrite_schema(value: &mut Value, renames: &BTreeMap<String, String>) -> Result<()> {
    match value {
        Value::Array(values) => {
            for value in values {
                rewrite_schema(value, renames)?;
            }
        }
        Value::Object(object) => {
            rewrite_schema_ref(object, renames)?;
            normalize_numeric_constraint(object, "minItems")?;
            normalize_numeric_constraint(object, "maxItems")?;

            for child in object.values_mut() {
                rewrite_schema(child, renames)?;
            }
        }
        _ => {}
    }

    Ok(())
}

fn normalize_unions(value: &mut Value, definitions: &Map<String, Value>) -> Result<()> {
    match value {
        Value::Array(values) => {
            for value in values {
                normalize_unions(value, definitions)?;
            }
        }
        Value::Object(object) => {
            for child in object.values_mut() {
                normalize_unions(child, definitions)?;
            }

            if let Some(any_of) = object.remove("anyOf") {
                let variants = any_of
                    .as_array()
                    .ok_or_else(|| invalid_data("anyOf must be an array"))?;
                if !is_safe_nullable_union(variants, definitions)? && !is_runner_union(variants) {
                    return Err(invalid_data(format!(
                        "unsupported anyOf shape: {}",
                        Value::Array(variants.clone())
                    ))
                    .into());
                }
                object.insert("oneOf".to_string(), any_of);
            }
        }
        _ => {}
    }

    Ok(())
}

fn rewrite_schema_ref(
    object: &mut Map<String, Value>,
    renames: &BTreeMap<String, String>,
) -> Result<()> {
    let Some(reference) = object.get_mut("$ref") else {
        return Ok(());
    };
    let reference = reference
        .as_str()
        .ok_or_else(|| invalid_data("$ref must be a string"))?;
    let Some(old_name) = reference.strip_prefix(SCHEMA_REF_PREFIX) else {
        return Ok(());
    };
    let new_name = renames
        .get(old_name)
        .ok_or_else(|| invalid_data(format!("reference points to unknown schema {old_name}")))?;
    *object
        .get_mut("$ref")
        .expect("$ref was read from this object") = Value::String(definition_ref(new_name));
    Ok(())
}

fn normalize_numeric_constraint(object: &mut Map<String, Value>, key: &str) -> Result<()> {
    let Some(value) = object.get_mut(key) else {
        return Ok(());
    };

    if let Value::String(number) = value {
        let number = number
            .parse::<u64>()
            .map_err(|error| invalid_data(format!("{key} value {number:?} is invalid: {error}")))?;
        *value = Value::from(number);
    }

    if !value.is_u64() {
        return Err(invalid_data(format!("{key} must be a non-negative integer")).into());
    }

    Ok(())
}

fn is_safe_nullable_union(variants: &[Value], definitions: &Map<String, Value>) -> Result<bool> {
    if variants.len() != 2 {
        return Ok(false);
    }

    let Some(null_index) = variants
        .iter()
        .position(|variant| variant.get("type").and_then(Value::as_str) == Some("null"))
    else {
        return Ok(false);
    };
    if variants
        .iter()
        .skip(null_index + 1)
        .any(|variant| variant.get("type").and_then(Value::as_str) == Some("null"))
    {
        return Ok(false);
    }

    let non_null_variant = variants
        .iter()
        .enumerate()
        .find_map(|(index, variant)| (index != null_index).then_some(variant))
        .ok_or_else(|| invalid_data("nullable union has no non-null branch"))?;
    schema_rejects_null(non_null_variant, definitions, &mut Vec::new())
}

fn schema_rejects_null(
    schema: &Value,
    definitions: &Map<String, Value>,
    resolving: &mut Vec<String>,
) -> Result<bool> {
    let Some(object) = schema.as_object() else {
        return Ok(schema == &Value::Bool(false));
    };

    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        let name = reference
            .strip_prefix(DEFINITION_REF_PREFIX)
            .ok_or_else(|| {
                invalid_data(format!(
                    "unsupported reference while checking nullability: {reference}"
                ))
            })?;
        if resolving.iter().any(|current| current == name) {
            return Ok(false);
        }
        let target = definitions.get(name).ok_or_else(|| {
            invalid_data(format!("reference points to unknown definition {name}"))
        })?;
        resolving.push(name.to_string());
        let rejects_null = schema_rejects_null(target, definitions, resolving)?;
        resolving.pop();
        return Ok(rejects_null);
    }

    if let Some(schema_type) = object.get("type") {
        return Ok(match schema_type {
            Value::String(schema_type) => schema_type != "null",
            Value::Array(types) => !types.iter().any(|value| value.as_str() == Some("null")),
            _ => false,
        });
    }
    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        return Ok(!values.contains(&Value::Null));
    }
    if let Some(value) = object.get("const") {
        return Ok(!value.is_null());
    }
    if let Some(all_of) = object.get("allOf").and_then(Value::as_array) {
        for variant in all_of {
            if schema_rejects_null(variant, definitions, resolving)? {
                return Ok(true);
            }
        }
    }
    for union_key in ["anyOf", "oneOf"] {
        if let Some(variants) = object.get(union_key).and_then(Value::as_array) {
            for variant in variants {
                if !schema_rejects_null(variant, definitions, resolving)? {
                    return Ok(false);
                }
            }
            return Ok(true);
        }
    }

    Ok(false)
}

fn validate_runner_definition(
    definitions: &Map<String, Value>,
    name: &str,
    expected_discriminator: &str,
) -> Result<()> {
    let schema = definitions.get(name).ok_or_else(|| {
        invalid_data(format!(
            "runner definition {name} is missing from the Wolf schema"
        ))
    })?;
    let object = schema
        .as_object()
        .filter(|schema| schema.get("type").and_then(Value::as_str) == Some("object"))
        .ok_or_else(|| invalid_data(format!("runner definition {name} must be an object")))?;
    let requires_type = object
        .get("required")
        .and_then(Value::as_array)
        .is_some_and(|required| required.iter().any(|field| field.as_str() == Some("type")));
    if !requires_type {
        return Err(invalid_data(format!(
            "runner definition {name} must require its type discriminator"
        ))
        .into());
    }

    let discriminator = object
        .get("properties")
        .and_then(Value::as_object)
        .and_then(|properties| properties.get("type"))
        .and_then(Value::as_object)
        .ok_or_else(|| invalid_data(format!("runner definition {name} has no type property")))?;
    let matches_expected = discriminator.get("const").and_then(Value::as_str)
        == Some(expected_discriminator)
        || discriminator
            .get("enum")
            .and_then(Value::as_array)
            .is_some_and(|values| {
                values.len() == 1 && values[0].as_str() == Some(expected_discriminator)
            });
    if !matches_expected {
        return Err(invalid_data(format!(
            "runner definition {name} must use the {expected_discriminator:?} type discriminator"
        ))
        .into());
    }

    Ok(())
}

fn is_runner_union(variants: &[Value]) -> bool {
    variants.len() == 2
        && variants.iter().any(|variant| {
            variant.get("$ref").and_then(Value::as_str) == Some(&definition_ref(APP_CMD_DEFINITION))
        })
        && variants.iter().any(|variant| {
            variant.get("$ref").and_then(Value::as_str)
                == Some(&definition_ref(APP_DOCKER_DEFINITION))
        })
}

fn hoist_runner_union(value: &mut Value, count: &mut usize) {
    if value
        .get("oneOf")
        .and_then(Value::as_array)
        .is_some_and(|variants| is_runner_union(variants))
    {
        *value = json!({"$ref": definition_ref(RUNNER_DEFINITION)});
        *count += 1;
        return;
    }

    match value {
        Value::Array(values) => {
            for value in values {
                hoist_runner_union(value, count);
            }
        }
        Value::Object(object) => {
            for value in object.values_mut() {
                hoist_runner_union(value, count);
            }
        }
        _ => {}
    }
}

fn definition_ref(name: &str) -> String {
    format!("{DEFINITION_REF_PREFIX}{name}")
}

fn invalid_data(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, message.into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_types_are_current() -> Result<()> {
        let paths = Paths::from_manifest_dir()?;
        let expected = generate_types(&paths.schema)?;
        let actual = fs::read_to_string(&paths.types)?;

        assert_eq!(
            actual, expected,
            "types.rs is stale; run `cargo run -p wolf-api-gen`"
        );
        Ok(())
    }

    #[test]
    fn rejects_schema_name_collisions() {
        let schemas = Map::from_iter([
            ("wolf__api__Thing".to_string(), json!({})),
            ("wolf__config__Thing".to_string(), json!({})),
        ]);

        let error = schema_renames(&schemas).expect_err("collision must be rejected");

        assert!(error.to_string().contains("both normalize to Thing"));
    }

    #[test]
    fn rejects_unknown_any_of_shapes() {
        let mut schema = json!({
            "anyOf": [
                {"type": "string"},
                {"type": "integer"}
            ]
        });

        let error = normalize_unions(&mut schema, &Map::new()).expect_err("union must fail");

        assert!(error.to_string().contains("unsupported anyOf shape"));
    }

    #[test]
    fn rejects_nullable_union_when_other_branch_can_accept_null() {
        let mut schema = json!({
            "anyOf": [
                {},
                {"type": "null"}
            ]
        });

        let error = normalize_unions(&mut schema, &Map::new())
            .expect_err("ambiguous nullable union must fail");

        assert!(error.to_string().contains("unsupported anyOf shape"));
    }

    #[test]
    fn checks_nullable_references_before_rewriting_union() -> Result<()> {
        let definitions = Map::from_iter([("StringValue".to_string(), json!({"type": "string"}))]);
        let mut schema = json!({
            "anyOf": [
                {"$ref": "#/definitions/StringValue"},
                {"type": "null"}
            ]
        });

        normalize_unions(&mut schema, &definitions)?;

        assert!(schema.get("anyOf").is_none());
        assert!(schema.get("oneOf").is_some());
        Ok(())
    }

    #[test]
    fn rejects_runner_without_required_discriminator() {
        let definitions = Map::from_iter([(
            APP_CMD_DEFINITION.to_string(),
            json!({
                "type": "object",
                "properties": {"type": {"enum": ["process"]}}
            }),
        )]);

        let error = validate_runner_definition(&definitions, APP_CMD_DEFINITION, "process")
            .expect_err("optional discriminator must fail");

        assert!(error.to_string().contains("must require"));
    }

    #[test]
    fn rejects_runner_with_wrong_discriminator() {
        let definitions = Map::from_iter([(
            APP_DOCKER_DEFINITION.to_string(),
            json!({
                "type": "object",
                "required": ["type"],
                "properties": {"type": {"enum": ["container"]}}
            }),
        )]);

        let error = validate_runner_definition(&definitions, APP_DOCKER_DEFINITION, "docker")
            .expect_err("wrong discriminator must fail");

        assert!(error.to_string().contains("\"docker\" type discriminator"));
    }
}
