// @generated by wolf-api-gen from its vendored OpenAPI schema; do not edit.
// Regenerate with: cargo run -p wolf-api-gen
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]
#![allow(missing_docs)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`App`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"av1_gst_pipeline\","]
#[doc = "    \"h264_gst_pipeline\","]
#[doc = "    \"hevc_gst_pipeline\","]
#[doc = "    \"id\","]
#[doc = "    \"opus_gst_pipeline\","]
#[doc = "    \"render_node\","]
#[doc = "    \"runner\","]
#[doc = "    \"start_audio_server\","]
#[doc = "    \"start_virtual_compositor\","]
#[doc = "    \"support_hdr\","]
#[doc = "    \"title\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"av1_gst_pipeline\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"h264_gst_pipeline\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"hevc_gst_pipeline\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"icon_png_path\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"opus_gst_pipeline\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"render_node\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"runner\": {"]
#[doc = "      \"$ref\": \"#/definitions/Runner\""]
#[doc = "    },"]
#[doc = "    \"start_audio_server\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"start_virtual_compositor\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"support_hdr\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"title\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct App {
    pub av1_gst_pipeline: ::std::string::String,
    pub h264_gst_pipeline: ::std::string::String,
    pub hevc_gst_pipeline: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub icon_png_path: ::std::option::Option<::std::string::String>,
    pub id: ::std::string::String,
    pub opus_gst_pipeline: ::std::string::String,
    pub render_node: ::std::string::String,
    pub runner: Runner,
    pub start_audio_server: bool,
    pub start_virtual_compositor: bool,
    pub support_hdr: bool,
    pub title: ::std::string::String,
}
#[doc = "`AppCmd`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"run_cmd\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"run_cmd\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"process\""]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppCmd {
    pub run_cmd: ::std::string::String,
    #[serde(rename = "type")]
    pub type_: AppCmdType,
}
#[doc = "`AppCmdType`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"process\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AppCmdType {
    #[serde(rename = "process")]
    Process,
}
impl ::std::fmt::Display for AppCmdType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Process => f.write_str("process"),
        }
    }
}
impl ::std::str::FromStr for AppCmdType {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "process" => Ok(Self::Process),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AppCmdType {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for AppCmdType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AppCmdType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`AppDeleteRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppDeleteRequest {
    pub id: ::std::string::String,
}
#[doc = "`AppDocker`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"devices\","]
#[doc = "    \"env\","]
#[doc = "    \"image\","]
#[doc = "    \"mounts\","]
#[doc = "    \"name\","]
#[doc = "    \"ports\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"base_create_json\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"devices\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"env\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"image\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"mounts\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"ports\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"docker\""]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppDocker {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub base_create_json: ::std::option::Option<::std::string::String>,
    pub devices: ::std::vec::Vec<::std::string::String>,
    pub env: ::std::vec::Vec<::std::string::String>,
    pub image: ::std::string::String,
    pub mounts: ::std::vec::Vec<::std::string::String>,
    pub name: ::std::string::String,
    pub ports: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "type")]
    pub type_: AppDockerType,
}
#[doc = "`AppDockerType`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"docker\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AppDockerType {
    #[serde(rename = "docker")]
    Docker,
}
impl ::std::fmt::Display for AppDockerType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Docker => f.write_str("docker"),
        }
    }
}
impl ::std::str::FromStr for AppDockerType {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "docker" => Ok(Self::Docker),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AppDockerType {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for AppDockerType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AppDockerType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`AppListResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"apps\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"apps\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/App\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppListResponse {
    pub apps: ::std::vec::Vec<App>,
    pub success: bool,
}
#[doc = "`AudioMode`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"bitrate\","]
#[doc = "    \"channels\","]
#[doc = "    \"coupled_streams\","]
#[doc = "    \"sample_rate\","]
#[doc = "    \"speakers\","]
#[doc = "    \"streams\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"bitrate\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"channels\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"coupled_streams\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"sample_rate\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"speakers\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"string\","]
#[doc = "        \"enum\": ["]
#[doc = "          \"FRONT_LEFT\","]
#[doc = "          \"FRONT_RIGHT\","]
#[doc = "          \"FRONT_CENTER\","]
#[doc = "          \"LOW_FREQUENCY\","]
#[doc = "          \"BACK_LEFT\","]
#[doc = "          \"BACK_RIGHT\","]
#[doc = "          \"SIDE_LEFT\","]
#[doc = "          \"SIDE_RIGHT\","]
#[doc = "          \"MAX_SPEAKERS\""]
#[doc = "        ]"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"streams\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AudioMode {
    pub bitrate: i64,
    pub channels: i64,
    pub coupled_streams: i64,
    pub sample_rate: i64,
    pub speakers: ::std::vec::Vec<AudioModeSpeakersItem>,
    pub streams: i64,
}
#[doc = "`AudioModeSpeakersItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"FRONT_LEFT\","]
#[doc = "    \"FRONT_RIGHT\","]
#[doc = "    \"FRONT_CENTER\","]
#[doc = "    \"LOW_FREQUENCY\","]
#[doc = "    \"BACK_LEFT\","]
#[doc = "    \"BACK_RIGHT\","]
#[doc = "    \"SIDE_LEFT\","]
#[doc = "    \"SIDE_RIGHT\","]
#[doc = "    \"MAX_SPEAKERS\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AudioModeSpeakersItem {
    #[serde(rename = "FRONT_LEFT")]
    FrontLeft,
    #[serde(rename = "FRONT_RIGHT")]
    FrontRight,
    #[serde(rename = "FRONT_CENTER")]
    FrontCenter,
    #[serde(rename = "LOW_FREQUENCY")]
    LowFrequency,
    #[serde(rename = "BACK_LEFT")]
    BackLeft,
    #[serde(rename = "BACK_RIGHT")]
    BackRight,
    #[serde(rename = "SIDE_LEFT")]
    SideLeft,
    #[serde(rename = "SIDE_RIGHT")]
    SideRight,
    #[serde(rename = "MAX_SPEAKERS")]
    MaxSpeakers,
}
impl ::std::fmt::Display for AudioModeSpeakersItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::FrontLeft => f.write_str("FRONT_LEFT"),
            Self::FrontRight => f.write_str("FRONT_RIGHT"),
            Self::FrontCenter => f.write_str("FRONT_CENTER"),
            Self::LowFrequency => f.write_str("LOW_FREQUENCY"),
            Self::BackLeft => f.write_str("BACK_LEFT"),
            Self::BackRight => f.write_str("BACK_RIGHT"),
            Self::SideLeft => f.write_str("SIDE_LEFT"),
            Self::SideRight => f.write_str("SIDE_RIGHT"),
            Self::MaxSpeakers => f.write_str("MAX_SPEAKERS"),
        }
    }
}
impl ::std::str::FromStr for AudioModeSpeakersItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "FRONT_LEFT" => Ok(Self::FrontLeft),
            "FRONT_RIGHT" => Ok(Self::FrontRight),
            "FRONT_CENTER" => Ok(Self::FrontCenter),
            "LOW_FREQUENCY" => Ok(Self::LowFrequency),
            "BACK_LEFT" => Ok(Self::BackLeft),
            "BACK_RIGHT" => Ok(Self::BackRight),
            "SIDE_LEFT" => Ok(Self::SideLeft),
            "SIDE_RIGHT" => Ok(Self::SideRight),
            "MAX_SPEAKERS" => Ok(Self::MaxSpeakers),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AudioModeSpeakersItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for AudioModeSpeakersItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AudioModeSpeakersItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`AudioSession`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"aes_iv\","]
#[doc = "    \"aes_key\","]
#[doc = "    \"audio_mode\","]
#[doc = "    \"client_ip\","]
#[doc = "    \"encrypt_audio\","]
#[doc = "    \"gst_pipeline\","]
#[doc = "    \"packet_duration\","]
#[doc = "    \"port\","]
#[doc = "    \"rtp_secret_payload\","]
#[doc = "    \"session_id\","]
#[doc = "    \"wait_for_ping\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"aes_iv\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"aes_key\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"audio_mode\": {"]
#[doc = "      \"$ref\": \"#/definitions/AudioMode\""]
#[doc = "    },"]
#[doc = "    \"client_ip\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"encrypt_audio\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"gst_pipeline\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"packet_duration\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"port\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"rtp_secret_payload\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"integer\""]
#[doc = "      },"]
#[doc = "      \"maxItems\": 16,"]
#[doc = "      \"minItems\": 16"]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"wait_for_ping\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AudioSession {
    pub aes_iv: ::std::string::String,
    pub aes_key: ::std::string::String,
    pub audio_mode: AudioMode,
    pub client_ip: ::std::string::String,
    pub encrypt_audio: bool,
    pub gst_pipeline: ::std::string::String,
    pub packet_duration: i64,
    pub port: i64,
    pub rtp_secret_payload: [i64; 16usize],
    pub session_id: ::std::string::String,
    pub wait_for_ping: bool,
}
#[doc = "`AudioSettings`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"channel_count\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"channel_count\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AudioSettings {
    pub channel_count: i64,
}
#[doc = "`ClientSettings`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"controllers_override\","]
#[doc = "    \"h_scroll_acceleration\","]
#[doc = "    \"motion_controller_override\","]
#[doc = "    \"mouse_acceleration\","]
#[doc = "    \"run_gid\","]
#[doc = "    \"run_uid\","]
#[doc = "    \"v_scroll_acceleration\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"controllers_override\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"string\","]
#[doc = "        \"enum\": ["]
#[doc = "          \"XBOX\","]
#[doc = "          \"PS\","]
#[doc = "          \"NINTENDO\","]
#[doc = "          \"AUTO\""]
#[doc = "        ]"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"h_scroll_acceleration\": {"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"motion_controller_override\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"XBOX\","]
#[doc = "        \"PS\","]
#[doc = "        \"NINTENDO\","]
#[doc = "        \"AUTO\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"mouse_acceleration\": {"]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"run_gid\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"run_uid\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"v_scroll_acceleration\": {"]
#[doc = "      \"type\": \"number\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct ClientSettings {
    pub controllers_override: ::std::vec::Vec<ClientSettingsControllersOverrideItem>,
    pub h_scroll_acceleration: f64,
    pub motion_controller_override: ClientSettingsMotionControllerOverride,
    pub mouse_acceleration: f64,
    pub run_gid: i64,
    pub run_uid: i64,
    pub v_scroll_acceleration: f64,
}
#[doc = "`ClientSettingsControllersOverrideItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"XBOX\","]
#[doc = "    \"PS\","]
#[doc = "    \"NINTENDO\","]
#[doc = "    \"AUTO\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ClientSettingsControllersOverrideItem {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for ClientSettingsControllersOverrideItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for ClientSettingsControllersOverrideItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ClientSettingsControllersOverrideItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for ClientSettingsControllersOverrideItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ClientSettingsControllersOverrideItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`ClientSettingsMotionControllerOverride`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"XBOX\","]
#[doc = "    \"PS\","]
#[doc = "    \"NINTENDO\","]
#[doc = "    \"AUTO\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ClientSettingsMotionControllerOverride {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for ClientSettingsMotionControllerOverride {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for ClientSettingsMotionControllerOverride {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ClientSettingsMotionControllerOverride {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for ClientSettingsMotionControllerOverride {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ClientSettingsMotionControllerOverride {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`CreateLobbyRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"audio_settings\","]
#[doc = "    \"client_settings\","]
#[doc = "    \"multi_user\","]
#[doc = "    \"name\","]
#[doc = "    \"pin\","]
#[doc = "    \"profile_id\","]
#[doc = "    \"runner\","]
#[doc = "    \"runner_state_folder\","]
#[doc = "    \"stop_when_everyone_leaves\","]
#[doc = "    \"video_settings\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"audio_settings\": {"]
#[doc = "      \"$ref\": \"#/definitions/AudioSettings\""]
#[doc = "    },"]
#[doc = "    \"client_settings\": {"]
#[doc = "      \"description\": \"Client settings to update (only specified fields will be updated)\","]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/definitions/PartialClientSettings\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"icon_png_path\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"multi_user\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"pin\": {"]
#[doc = "      \"description\": \"If present, the pin that is required to join the lobby.If this is not set, then the lobby is open to everyone\","]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"array\","]
#[doc = "          \"items\": {"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"profile_id\": {"]
#[doc = "      \"description\": \"The profile that originally created the lobby\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"runner\": {"]
#[doc = "      \"$ref\": \"#/definitions/Runner\""]
#[doc = "    },"]
#[doc = "    \"runner_state_folder\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"stop_when_everyone_leaves\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"video_settings\": {"]
#[doc = "      \"$ref\": \"#/definitions/VideoSettings\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct CreateLobbyRequest {
    pub audio_settings: AudioSettings,
    #[doc = "Client settings to update (only specified fields will be updated)"]
    pub client_settings: ::std::option::Option<PartialClientSettings>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub icon_png_path: ::std::option::Option<::std::string::String>,
    pub multi_user: bool,
    pub name: ::std::string::String,
    #[doc = "If present, the pin that is required to join the lobby.If this is not set, then the lobby is open to everyone"]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
    #[doc = "The profile that originally created the lobby"]
    pub profile_id: ::std::string::String,
    pub runner: Runner,
    pub runner_state_folder: ::std::string::String,
    pub stop_when_everyone_leaves: bool,
    pub video_settings: VideoSettings,
}
#[doc = "`DisplayMode`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"height\","]
#[doc = "    \"refreshRate\","]
#[doc = "    \"width\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"height\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"refreshRate\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"width\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DisplayMode {
    pub height: i64,
    #[serde(rename = "refreshRate")]
    pub refresh_rate: i64,
    pub width: i64,
}
#[doc = "`DockerPullImageRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"image_name\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"image_name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DockerPullImageRequest {
    pub image_name: ::std::string::String,
}
#[doc = "`DockerPullImageResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DockerPullImageResponse {
    pub success: bool,
}
#[doc = "`GenericErrorResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"error\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"error\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct GenericErrorResponse {
    pub error: ::std::string::String,
    pub success: bool,
}
#[doc = "`GenericSuccessResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct GenericSuccessResponse {
    pub success: bool,
}
#[doc = "`JoinLobbyEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"lobby_id\","]
#[doc = "    \"moonlight_session_id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"lobby_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"moonlight_session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"pin\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"array\","]
#[doc = "          \"items\": {"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct JoinLobbyEvent {
    pub lobby_id: ::std::string::String,
    pub moonlight_session_id: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
}
#[doc = "`LeaveLobbyEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"lobby_id\","]
#[doc = "    \"moonlight_session_id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"lobby_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"moonlight_session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct LeaveLobbyEvent {
    pub lobby_id: ::std::string::String,
    pub moonlight_session_id: ::std::string::String,
}
#[doc = "`LobbiesResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"lobbies\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"lobbies\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/Lobby\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct LobbiesResponse {
    pub lobbies: ::std::vec::Vec<Lobby>,
    pub success: bool,
}
#[doc = "`Lobby`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"connected_sessions\","]
#[doc = "    \"id\","]
#[doc = "    \"multi_user\","]
#[doc = "    \"name\","]
#[doc = "    \"pin_required\","]
#[doc = "    \"runner\","]
#[doc = "    \"started_by_profile_id\","]
#[doc = "    \"stop_when_everyone_leaves\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"connected_sessions\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"string\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"icon_png_path\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"multi_user\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"pin_required\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    },"]
#[doc = "    \"runner\": {"]
#[doc = "      \"$ref\": \"#/definitions/Runner\""]
#[doc = "    },"]
#[doc = "    \"started_by_profile_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"stop_when_everyone_leaves\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct Lobby {
    pub connected_sessions: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub icon_png_path: ::std::option::Option<::std::string::String>,
    pub id: ::std::string::String,
    pub multi_user: bool,
    pub name: ::std::string::String,
    pub pin_required: bool,
    pub runner: Runner,
    pub started_by_profile_id: ::std::string::String,
    pub stop_when_everyone_leaves: bool,
}
#[doc = "`LobbyCreateResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"lobby_id\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"lobby_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct LobbyCreateResponse {
    pub lobby_id: ::std::string::String,
    pub success: bool,
}
#[doc = "`PairRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"pair_secret\","]
#[doc = "    \"pin\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"pair_secret\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"pin\": {"]
#[doc = "      \"description\": \"The PIN created by the remote Moonlight client\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PairRequest {
    pub pair_secret: ::std::string::String,
    #[doc = "The PIN created by the remote Moonlight client"]
    pub pin: ::std::string::String,
}
#[doc = "`PairedClient`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"app_state_folder\","]
#[doc = "    \"client_id\","]
#[doc = "    \"settings\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"app_state_folder\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"client_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"settings\": {"]
#[doc = "      \"$ref\": \"#/definitions/ClientSettings\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PairedClient {
    pub app_state_folder: ::std::string::String,
    pub client_id: ::std::string::String,
    pub settings: ClientSettings,
}
#[doc = "`PairedClientsResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"clients\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"clients\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/PairedClient\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PairedClientsResponse {
    pub clients: ::std::vec::Vec<PairedClient>,
    pub success: bool,
}
#[doc = "`PartialClientSettings`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"properties\": {"]
#[doc = "    \"controllers_override\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"array\","]
#[doc = "          \"items\": {"]
#[doc = "            \"type\": \"string\","]
#[doc = "            \"enum\": ["]
#[doc = "              \"XBOX\","]
#[doc = "              \"PS\","]
#[doc = "              \"NINTENDO\","]
#[doc = "              \"AUTO\""]
#[doc = "            ]"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"h_scroll_acceleration\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"number\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"motion_controller_override\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\","]
#[doc = "          \"enum\": ["]
#[doc = "            \"XBOX\","]
#[doc = "            \"PS\","]
#[doc = "            \"NINTENDO\","]
#[doc = "            \"AUTO\""]
#[doc = "          ]"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"mouse_acceleration\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"number\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"run_gid\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"run_uid\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"integer\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"v_scroll_acceleration\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"number\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PartialClientSettings {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub controllers_override:
        ::std::option::Option<::std::vec::Vec<PartialClientSettingsControllersOverrideItem>>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub h_scroll_acceleration: ::std::option::Option<f64>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub motion_controller_override:
        ::std::option::Option<PartialClientSettingsMotionControllerOverride>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub mouse_acceleration: ::std::option::Option<f64>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub run_gid: ::std::option::Option<i64>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub run_uid: ::std::option::Option<i64>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub v_scroll_acceleration: ::std::option::Option<f64>,
}
impl ::std::default::Default for PartialClientSettings {
    fn default() -> Self {
        Self {
            controllers_override: Default::default(),
            h_scroll_acceleration: Default::default(),
            motion_controller_override: Default::default(),
            mouse_acceleration: Default::default(),
            run_gid: Default::default(),
            run_uid: Default::default(),
            v_scroll_acceleration: Default::default(),
        }
    }
}
#[doc = "`PartialClientSettingsControllersOverrideItem`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"XBOX\","]
#[doc = "    \"PS\","]
#[doc = "    \"NINTENDO\","]
#[doc = "    \"AUTO\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum PartialClientSettingsControllersOverrideItem {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for PartialClientSettingsControllersOverrideItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for PartialClientSettingsControllersOverrideItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for PartialClientSettingsControllersOverrideItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String>
    for PartialClientSettingsControllersOverrideItem
{
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
    for PartialClientSettingsControllersOverrideItem
{
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`PartialClientSettingsMotionControllerOverride`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"XBOX\","]
#[doc = "    \"PS\","]
#[doc = "    \"NINTENDO\","]
#[doc = "    \"AUTO\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum PartialClientSettingsMotionControllerOverride {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for PartialClientSettingsMotionControllerOverride {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for PartialClientSettingsMotionControllerOverride {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for PartialClientSettingsMotionControllerOverride {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String>
    for PartialClientSettingsMotionControllerOverride
{
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
    for PartialClientSettingsMotionControllerOverride
{
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`PendingPairClient`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"client_ip\","]
#[doc = "    \"pair_secret\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"client_ip\": {"]
#[doc = "      \"description\": \"The IP of the remote Moonlight client\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"pair_secret\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PendingPairClient {
    #[doc = "The IP of the remote Moonlight client"]
    pub client_ip: ::std::string::String,
    pub pair_secret: ::std::string::String,
}
#[doc = "`PendingPairRequestsResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"requests\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"requests\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/PendingPairClient\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PendingPairRequestsResponse {
    pub requests: ::std::vec::Vec<PendingPairClient>,
    pub success: bool,
}
#[doc = "`Profile`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"apps\","]
#[doc = "    \"icon_png_path\","]
#[doc = "    \"id\","]
#[doc = "    \"name\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"apps\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/App\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"icon_png_path\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"pin\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"array\","]
#[doc = "          \"items\": {"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct Profile {
    pub apps: ::std::vec::Vec<App>,
    pub icon_png_path: ::std::string::String,
    pub id: ::std::string::String,
    pub name: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
}
#[doc = "`ProfileListResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"profiles\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"profiles\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/Profile\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct ProfileListResponse {
    pub profiles: ::std::vec::Vec<Profile>,
    pub success: bool,
}
#[doc = "`ProfileRemoveRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct ProfileRemoveRequest {
    pub id: ::std::string::String,
}
#[doc = "`Runner`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"oneOf\": ["]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/definitions/AppCMD\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/definitions/AppDocker\""]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
#[serde(untagged)]
pub enum Runner {
    Cmd(AppCmd),
    Docker(AppDocker),
}
impl ::std::convert::From<AppCmd> for Runner {
    fn from(value: AppCmd) -> Self {
        Self::Cmd(value)
    }
}
impl ::std::convert::From<AppDocker> for Runner {
    fn from(value: AppDocker) -> Self {
        Self::Docker(value)
    }
}
#[doc = "`RunnerStartRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"runner\","]
#[doc = "    \"session_id\","]
#[doc = "    \"stop_stream_when_over\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"runner\": {"]
#[doc = "      \"$ref\": \"#/definitions/Runner\""]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"stop_stream_when_over\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct RunnerStartRequest {
    pub runner: Runner,
    pub session_id: ::std::string::String,
    pub stop_stream_when_over: bool,
}
#[doc = "`StopLobbyEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"lobby_id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"lobby_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"pin\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"array\","]
#[doc = "          \"items\": {"]
#[doc = "            \"type\": \"integer\""]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StopLobbyEvent {
    pub lobby_id: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
}
#[doc = "`StreamSession`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"aes_iv\","]
#[doc = "    \"aes_key\","]
#[doc = "    \"audio_channel_count\","]
#[doc = "    \"client_ip\","]
#[doc = "    \"rtsp_fake_ip\","]
#[doc = "    \"video_height\","]
#[doc = "    \"video_refresh_rate\","]
#[doc = "    \"video_width\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"aes_iv\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"aes_key\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"app_id\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"audio_channel_count\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"client_id\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"client_ip\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"client_settings\": {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/definitions/ClientSettings\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"rtsp_fake_ip\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"video_height\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"video_refresh_rate\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"video_width\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSession {
    pub aes_iv: ::std::string::String,
    pub aes_key: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub app_id: ::std::option::Option<::std::string::String>,
    pub audio_channel_count: i64,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub client_id: ::std::option::Option<::std::string::String>,
    pub client_ip: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub client_settings: ::std::option::Option<ClientSettings>,
    pub rtsp_fake_ip: ::std::string::String,
    pub video_height: i64,
    pub video_refresh_rate: i64,
    pub video_width: i64,
}
#[doc = "`StreamSessionCreated`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"session_id\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionCreated {
    pub session_id: ::std::string::String,
    pub success: bool,
}
#[doc = "`StreamSessionHandleInputRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"input_packet_hex\","]
#[doc = "    \"session_id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"input_packet_hex\": {"]
#[doc = "      \"description\": \"A HEX encoded Moonlight input packet, for the full format see: games-on-whales.github.io/wolf/stable/protocols/input-data.html\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionHandleInputRequest {
    #[doc = "A HEX encoded Moonlight input packet, for the full format see: games-on-whales.github.io/wolf/stable/protocols/input-data.html"]
    pub input_packet_hex: ::std::string::String,
    pub session_id: ::std::string::String,
}
#[doc = "`StreamSessionListResponse`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"sessions\","]
#[doc = "    \"success\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"sessions\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/StreamSession\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionListResponse {
    pub sessions: ::std::vec::Vec<StreamSession>,
    pub success: bool,
}
#[doc = "`StreamSessionPauseRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"session_id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionPauseRequest {
    pub session_id: ::std::string::String,
}
#[doc = "`StreamSessionStartRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"audio_session\","]
#[doc = "    \"session_id\","]
#[doc = "    \"video_session\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"audio_session\": {"]
#[doc = "      \"$ref\": \"#/definitions/AudioSession\""]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"video_session\": {"]
#[doc = "      \"$ref\": \"#/definitions/VideoSession\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionStartRequest {
    pub audio_session: AudioSession,
    pub session_id: ::std::string::String,
    pub video_session: VideoSession,
}
#[doc = "`StreamSessionStopRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"session_id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionStopRequest {
    pub session_id: ::std::string::String,
}
#[doc = "`UnpairClientRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"client_id\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"client_id\": {"]
#[doc = "      \"description\": \"The client ID to unpair\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct UnpairClientRequest {
    #[doc = "The client ID to unpair"]
    pub client_id: ::std::string::String,
}
#[doc = "`UpdateClientSettingsRequest`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"app_state_folder\","]
#[doc = "    \"client_id\","]
#[doc = "    \"settings\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"app_state_folder\": {"]
#[doc = "      \"description\": \"New app state folder path (optional)\","]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"client_id\": {"]
#[doc = "      \"description\": \"The client ID to identify the client (derived from certificate)\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"settings\": {"]
#[doc = "      \"description\": \"Client settings to update (only specified fields will be updated)\","]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/definitions/PartialClientSettings\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct UpdateClientSettingsRequest {
    #[doc = "New app state folder path (optional)"]
    pub app_state_folder: ::std::option::Option<::std::string::String>,
    #[doc = "The client ID to identify the client (derived from certificate)"]
    pub client_id: ::std::string::String,
    #[doc = "Client settings to update (only specified fields will be updated)"]
    pub settings: ::std::option::Option<PartialClientSettings>,
}
#[doc = "`VideoSession`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"bitrate_kbps\","]
#[doc = "    \"client_ip\","]
#[doc = "    \"color_range\","]
#[doc = "    \"color_space\","]
#[doc = "    \"display_mode\","]
#[doc = "    \"fec_percentage\","]
#[doc = "    \"frames_with_invalid_ref_threshold\","]
#[doc = "    \"gst_pipeline\","]
#[doc = "    \"min_required_fec_packets\","]
#[doc = "    \"packet_size\","]
#[doc = "    \"port\","]
#[doc = "    \"render_node\","]
#[doc = "    \"rtp_secret_payload\","]
#[doc = "    \"session_id\","]
#[doc = "    \"slices_per_frame\","]
#[doc = "    \"timeout_ms\","]
#[doc = "    \"wait_for_ping\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"bitrate_kbps\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"client_ip\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"color_range\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"JPEG\","]
#[doc = "        \"MPEG\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"color_space\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"BT601\","]
#[doc = "        \"BT709\","]
#[doc = "        \"BT2020\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"display_mode\": {"]
#[doc = "      \"$ref\": \"#/definitions/DisplayMode\""]
#[doc = "    },"]
#[doc = "    \"fec_percentage\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"frames_with_invalid_ref_threshold\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"gst_pipeline\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"min_required_fec_packets\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"packet_size\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"port\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"render_node\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"rtp_secret_payload\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"type\": \"integer\""]
#[doc = "      },"]
#[doc = "      \"maxItems\": 16,"]
#[doc = "      \"minItems\": 16"]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"slices_per_frame\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"timeout_ms\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"wait_for_ping\": {"]
#[doc = "      \"type\": \"boolean\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct VideoSession {
    pub bitrate_kbps: i64,
    pub client_ip: ::std::string::String,
    pub color_range: VideoSessionColorRange,
    pub color_space: VideoSessionColorSpace,
    pub display_mode: DisplayMode,
    pub fec_percentage: i64,
    pub frames_with_invalid_ref_threshold: i64,
    pub gst_pipeline: ::std::string::String,
    pub min_required_fec_packets: i64,
    pub packet_size: i64,
    pub port: i64,
    pub render_node: ::std::string::String,
    pub rtp_secret_payload: [i64; 16usize],
    pub session_id: ::std::string::String,
    pub slices_per_frame: i64,
    pub timeout_ms: i64,
    pub wait_for_ping: bool,
}
#[doc = "`VideoSessionColorRange`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"JPEG\","]
#[doc = "    \"MPEG\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum VideoSessionColorRange {
    #[serde(rename = "JPEG")]
    Jpeg,
    #[serde(rename = "MPEG")]
    Mpeg,
}
impl ::std::fmt::Display for VideoSessionColorRange {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Jpeg => f.write_str("JPEG"),
            Self::Mpeg => f.write_str("MPEG"),
        }
    }
}
impl ::std::str::FromStr for VideoSessionColorRange {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "JPEG" => Ok(Self::Jpeg),
            "MPEG" => Ok(Self::Mpeg),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for VideoSessionColorRange {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for VideoSessionColorRange {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for VideoSessionColorRange {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`VideoSessionColorSpace`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"BT601\","]
#[doc = "    \"BT709\","]
#[doc = "    \"BT2020\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum VideoSessionColorSpace {
    #[serde(rename = "BT601")]
    Bt601,
    #[serde(rename = "BT709")]
    Bt709,
    #[serde(rename = "BT2020")]
    Bt2020,
}
impl ::std::fmt::Display for VideoSessionColorSpace {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Bt601 => f.write_str("BT601"),
            Self::Bt709 => f.write_str("BT709"),
            Self::Bt2020 => f.write_str("BT2020"),
        }
    }
}
impl ::std::str::FromStr for VideoSessionColorSpace {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "BT601" => Ok(Self::Bt601),
            "BT709" => Ok(Self::Bt709),
            "BT2020" => Ok(Self::Bt2020),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for VideoSessionColorSpace {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for VideoSessionColorSpace {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for VideoSessionColorSpace {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`VideoSettings`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"height\","]
#[doc = "    \"refresh_rate\","]
#[doc = "    \"runner_render_node\","]
#[doc = "    \"video_producer_buffer_caps\","]
#[doc = "    \"wayland_render_node\","]
#[doc = "    \"width\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"height\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"refresh_rate\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"runner_render_node\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"video_producer_buffer_caps\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"wayland_render_node\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"width\": {"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct VideoSettings {
    pub height: i64,
    pub refresh_rate: i64,
    pub runner_render_node: ::std::string::String,
    pub video_producer_buffer_caps: ::std::string::String,
    pub wayland_render_node: ::std::string::String,
    pub width: i64,
}
#[doc = "`WolfApiTypes`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"WolfApiTypes\","]
#[doc = "  \"type\": \"object\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
#[serde(transparent)]
pub struct WolfApiTypes(pub ::serde_json::Map<::std::string::String, ::serde_json::Value>);
impl ::std::ops::Deref for WolfApiTypes {
    type Target = ::serde_json::Map<::std::string::String, ::serde_json::Value>;
    fn deref(&self) -> &::serde_json::Map<::std::string::String, ::serde_json::Value> {
        &self.0
    }
}
impl ::std::convert::From<WolfApiTypes>
    for ::serde_json::Map<::std::string::String, ::serde_json::Value>
{
    fn from(value: WolfApiTypes) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Map<::std::string::String, ::serde_json::Value>>
    for WolfApiTypes
{
    fn from(value: ::serde_json::Map<::std::string::String, ::serde_json::Value>) -> Self {
        Self(value)
    }
}
