// @generated by wolf-api-gen from its vendored OpenAPI schema; do not edit.
// Regenerate with: cargo run -p wolf-api-gen
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]
#![allow(missing_docs)]

#[doc = "`App`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct App {
    pub av1_gst_pipeline: ::std::string::String,
    pub h264_gst_pipeline: ::std::string::String,
    pub hevc_gst_pipeline: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub icon_png_path: ::std::option::Option<::std::string::String>,
    pub id: ::std::string::String,
    pub opus_gst_pipeline: ::std::string::String,
    pub render_node: ::std::string::String,
    pub runner: Runner,
    pub start_audio_server: bool,
    pub start_virtual_compositor: bool,
    pub support_hdr: bool,
    pub title: ::std::string::String,
}
#[doc = "`AppCmd`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppCmd {
    pub run_cmd: ::std::string::String,
    #[serde(rename = "type")]
    pub type_: AppCmdType,
}
#[doc = "`AppCmdType`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AppCmdType {
    #[serde(rename = "process")]
    Process,
}
impl ::std::fmt::Display for AppCmdType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Process => f.write_str("process"),
        }
    }
}
impl ::std::str::FromStr for AppCmdType {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "process" => Ok(Self::Process),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AppCmdType {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AppCmdType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`AppDeleteRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppDeleteRequest {
    pub id: ::std::string::String,
}
#[doc = "`AppDocker`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppDocker {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub base_create_json: ::std::option::Option<::std::string::String>,
    pub devices: ::std::vec::Vec<::std::string::String>,
    pub env: ::std::vec::Vec<::std::string::String>,
    pub image: ::std::string::String,
    pub mounts: ::std::vec::Vec<::std::string::String>,
    pub name: ::std::string::String,
    pub ports: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "type")]
    pub type_: AppDockerType,
}
#[doc = "`AppDockerType`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AppDockerType {
    #[serde(rename = "docker")]
    Docker,
}
impl ::std::fmt::Display for AppDockerType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Docker => f.write_str("docker"),
        }
    }
}
impl ::std::str::FromStr for AppDockerType {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "docker" => Ok(Self::Docker),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AppDockerType {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AppDockerType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`AppListResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AppListResponse {
    pub apps: ::std::vec::Vec<App>,
    pub success: bool,
}
#[doc = "`AudioMode`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AudioMode {
    pub bitrate: i64,
    pub channels: i64,
    pub coupled_streams: i64,
    pub sample_rate: i64,
    pub speakers: ::std::vec::Vec<AudioModeSpeakersItem>,
    pub streams: i64,
}
#[doc = "`AudioModeSpeakersItem`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AudioModeSpeakersItem {
    #[serde(rename = "FRONT_LEFT")]
    FrontLeft,
    #[serde(rename = "FRONT_RIGHT")]
    FrontRight,
    #[serde(rename = "FRONT_CENTER")]
    FrontCenter,
    #[serde(rename = "LOW_FREQUENCY")]
    LowFrequency,
    #[serde(rename = "BACK_LEFT")]
    BackLeft,
    #[serde(rename = "BACK_RIGHT")]
    BackRight,
    #[serde(rename = "SIDE_LEFT")]
    SideLeft,
    #[serde(rename = "SIDE_RIGHT")]
    SideRight,
    #[serde(rename = "MAX_SPEAKERS")]
    MaxSpeakers,
}
impl ::std::fmt::Display for AudioModeSpeakersItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::FrontLeft => f.write_str("FRONT_LEFT"),
            Self::FrontRight => f.write_str("FRONT_RIGHT"),
            Self::FrontCenter => f.write_str("FRONT_CENTER"),
            Self::LowFrequency => f.write_str("LOW_FREQUENCY"),
            Self::BackLeft => f.write_str("BACK_LEFT"),
            Self::BackRight => f.write_str("BACK_RIGHT"),
            Self::SideLeft => f.write_str("SIDE_LEFT"),
            Self::SideRight => f.write_str("SIDE_RIGHT"),
            Self::MaxSpeakers => f.write_str("MAX_SPEAKERS"),
        }
    }
}
impl ::std::str::FromStr for AudioModeSpeakersItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "FRONT_LEFT" => Ok(Self::FrontLeft),
            "FRONT_RIGHT" => Ok(Self::FrontRight),
            "FRONT_CENTER" => Ok(Self::FrontCenter),
            "LOW_FREQUENCY" => Ok(Self::LowFrequency),
            "BACK_LEFT" => Ok(Self::BackLeft),
            "BACK_RIGHT" => Ok(Self::BackRight),
            "SIDE_LEFT" => Ok(Self::SideLeft),
            "SIDE_RIGHT" => Ok(Self::SideRight),
            "MAX_SPEAKERS" => Ok(Self::MaxSpeakers),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AudioModeSpeakersItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AudioModeSpeakersItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`AudioSession`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AudioSession {
    pub aes_iv: ::std::string::String,
    pub aes_key: ::std::string::String,
    pub audio_mode: AudioMode,
    pub client_ip: ::std::string::String,
    pub encrypt_audio: bool,
    pub gst_pipeline: ::std::string::String,
    pub packet_duration: i64,
    pub port: i64,
    pub rtp_secret_payload: [i64; 16usize],
    pub session_id: ::std::string::String,
    pub wait_for_ping: bool,
}
#[doc = "`AudioSettings`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct AudioSettings {
    pub channel_count: i64,
}
#[doc = "`ClientSettings`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct ClientSettings {
    pub controllers_override: ::std::vec::Vec<ClientSettingsControllersOverrideItem>,
    pub h_scroll_acceleration: f64,
    pub motion_controller_override: ClientSettingsMotionControllerOverride,
    pub mouse_acceleration: f64,
    pub run_gid: i64,
    pub run_uid: i64,
    pub v_scroll_acceleration: f64,
}
#[doc = "`ClientSettingsControllersOverrideItem`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ClientSettingsControllersOverrideItem {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for ClientSettingsControllersOverrideItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for ClientSettingsControllersOverrideItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ClientSettingsControllersOverrideItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ClientSettingsControllersOverrideItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`ClientSettingsMotionControllerOverride`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ClientSettingsMotionControllerOverride {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for ClientSettingsMotionControllerOverride {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for ClientSettingsMotionControllerOverride {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ClientSettingsMotionControllerOverride {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ClientSettingsMotionControllerOverride {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`CreateLobbyRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct CreateLobbyRequest {
    pub audio_settings: AudioSettings,
    #[doc = "Client settings to update (only specified fields will be updated)"]
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub client_settings: ::std::option::Option<PartialClientSettings>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub icon_png_path: ::std::option::Option<::std::string::String>,
    pub multi_user: bool,
    pub name: ::std::string::String,
    #[doc = "If present, the pin that is required to join the lobby.If this is not set, then the lobby is open to everyone"]
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
    #[doc = "The profile that originally created the lobby"]
    pub profile_id: ::std::string::String,
    pub runner: Runner,
    pub runner_state_folder: ::std::string::String,
    pub stop_when_everyone_leaves: bool,
    pub video_settings: VideoSettings,
}
#[doc = "`DisplayMode`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DisplayMode {
    pub height: i64,
    #[serde(rename = "refreshRate")]
    pub refresh_rate: i64,
    pub width: i64,
}
#[doc = "`DockerPullImageRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DockerPullImageRequest {
    pub image_name: ::std::string::String,
}
#[doc = "`DockerPullImageResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DockerPullImageResponse {
    pub success: bool,
}
#[doc = "`GenericErrorResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct GenericErrorResponse {
    pub error: ::std::string::String,
    pub success: bool,
}
#[doc = "`GenericSuccessResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct GenericSuccessResponse {
    pub success: bool,
}
#[doc = "`JoinLobbyEvent`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct JoinLobbyEvent {
    pub lobby_id: ::std::string::String,
    pub moonlight_session_id: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
}
#[doc = "`LeaveLobbyEvent`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct LeaveLobbyEvent {
    pub lobby_id: ::std::string::String,
    pub moonlight_session_id: ::std::string::String,
}
#[doc = "`LobbiesResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct LobbiesResponse {
    pub lobbies: ::std::vec::Vec<Lobby>,
    pub success: bool,
}
#[doc = "`Lobby`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct Lobby {
    pub connected_sessions: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub icon_png_path: ::std::option::Option<::std::string::String>,
    pub id: ::std::string::String,
    pub multi_user: bool,
    pub name: ::std::string::String,
    pub pin_required: bool,
    pub runner: Runner,
    pub started_by_profile_id: ::std::string::String,
    pub stop_when_everyone_leaves: bool,
}
#[doc = "`LobbyCreateResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct LobbyCreateResponse {
    pub lobby_id: ::std::string::String,
    pub success: bool,
}
#[doc = "`PairRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PairRequest {
    pub pair_secret: ::std::string::String,
    #[doc = "The PIN created by the remote Moonlight client"]
    pub pin: ::std::string::String,
}
#[doc = "`PairedClient`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PairedClient {
    pub app_state_folder: ::std::string::String,
    pub client_id: ::std::string::String,
    pub settings: ClientSettings,
}
#[doc = "`PairedClientsResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PairedClientsResponse {
    pub clients: ::std::vec::Vec<PairedClient>,
    pub success: bool,
}
#[doc = "`PartialClientSettings`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, Default, PartialEq)]
pub struct PartialClientSettings {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub controllers_override:
        ::std::option::Option<::std::vec::Vec<PartialClientSettingsControllersOverrideItem>>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub h_scroll_acceleration: ::std::option::Option<f64>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub motion_controller_override:
        ::std::option::Option<PartialClientSettingsMotionControllerOverride>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub mouse_acceleration: ::std::option::Option<f64>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub run_gid: ::std::option::Option<i64>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub run_uid: ::std::option::Option<i64>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub v_scroll_acceleration: ::std::option::Option<f64>,
}
#[doc = "`PartialClientSettingsControllersOverrideItem`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum PartialClientSettingsControllersOverrideItem {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for PartialClientSettingsControllersOverrideItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for PartialClientSettingsControllersOverrideItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for PartialClientSettingsControllersOverrideItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
    for PartialClientSettingsControllersOverrideItem
{
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`PartialClientSettingsMotionControllerOverride`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum PartialClientSettingsMotionControllerOverride {
    #[serde(rename = "XBOX")]
    Xbox,
    #[serde(rename = "PS")]
    Ps,
    #[serde(rename = "NINTENDO")]
    Nintendo,
    #[serde(rename = "AUTO")]
    Auto,
}
impl ::std::fmt::Display for PartialClientSettingsMotionControllerOverride {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Xbox => f.write_str("XBOX"),
            Self::Ps => f.write_str("PS"),
            Self::Nintendo => f.write_str("NINTENDO"),
            Self::Auto => f.write_str("AUTO"),
        }
    }
}
impl ::std::str::FromStr for PartialClientSettingsMotionControllerOverride {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "XBOX" => Ok(Self::Xbox),
            "PS" => Ok(Self::Ps),
            "NINTENDO" => Ok(Self::Nintendo),
            "AUTO" => Ok(Self::Auto),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for PartialClientSettingsMotionControllerOverride {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
    for PartialClientSettingsMotionControllerOverride
{
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`PendingPairClient`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PendingPairClient {
    #[doc = "The IP of the remote Moonlight client"]
    pub client_ip: ::std::string::String,
    pub pair_secret: ::std::string::String,
}
#[doc = "`PendingPairRequestsResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PendingPairRequestsResponse {
    pub requests: ::std::vec::Vec<PendingPairClient>,
    pub success: bool,
}
#[doc = "`Profile`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct Profile {
    pub apps: ::std::vec::Vec<App>,
    pub icon_png_path: ::std::string::String,
    pub id: ::std::string::String,
    pub name: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
}
#[doc = "`ProfileListResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct ProfileListResponse {
    pub profiles: ::std::vec::Vec<Profile>,
    pub success: bool,
}
#[doc = "`ProfileRemoveRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct ProfileRemoveRequest {
    pub id: ::std::string::String,
}
#[doc = "`Runner`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
#[serde(untagged)]
pub enum Runner {
    Cmd(AppCmd),
    Docker(AppDocker),
}
impl ::std::convert::From<AppCmd> for Runner {
    fn from(value: AppCmd) -> Self {
        Self::Cmd(value)
    }
}
impl ::std::convert::From<AppDocker> for Runner {
    fn from(value: AppDocker) -> Self {
        Self::Docker(value)
    }
}
#[doc = "`RunnerStartRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct RunnerStartRequest {
    pub runner: Runner,
    pub session_id: ::std::string::String,
    pub stop_stream_when_over: bool,
}
#[doc = "`StopLobbyEvent`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StopLobbyEvent {
    pub lobby_id: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub pin: ::std::option::Option<::std::vec::Vec<i64>>,
}
#[doc = "`StreamSession`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSession {
    pub aes_iv: ::std::string::String,
    pub aes_key: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub app_id: ::std::option::Option<::std::string::String>,
    pub audio_channel_count: i64,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub client_id: ::std::option::Option<::std::string::String>,
    pub client_ip: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub client_settings: ::std::option::Option<ClientSettings>,
    pub rtsp_fake_ip: ::std::string::String,
    pub video_height: i64,
    pub video_refresh_rate: i64,
    pub video_width: i64,
}
#[doc = "`StreamSessionCreated`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionCreated {
    pub session_id: ::std::string::String,
    pub success: bool,
}
#[doc = "`StreamSessionHandleInputRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionHandleInputRequest {
    #[doc = "A HEX encoded Moonlight input packet, for the full format see: games-on-whales.github.io/wolf/stable/protocols/input-data.html"]
    pub input_packet_hex: ::std::string::String,
    pub session_id: ::std::string::String,
}
#[doc = "`StreamSessionListResponse`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionListResponse {
    pub sessions: ::std::vec::Vec<StreamSession>,
    pub success: bool,
}
#[doc = "`StreamSessionPauseRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionPauseRequest {
    pub session_id: ::std::string::String,
}
#[doc = "`StreamSessionStartRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionStartRequest {
    pub audio_session: AudioSession,
    pub session_id: ::std::string::String,
    pub video_session: VideoSession,
}
#[doc = "`StreamSessionStopRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct StreamSessionStopRequest {
    pub session_id: ::std::string::String,
}
#[doc = "`UnpairClientRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct UnpairClientRequest {
    #[doc = "The client ID to unpair"]
    pub client_id: ::std::string::String,
}
#[doc = "`UpdateClientSettingsRequest`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct UpdateClientSettingsRequest {
    #[doc = "New app state folder path (optional)"]
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub app_state_folder: ::std::option::Option<::std::string::String>,
    #[doc = "The client ID to identify the client (derived from certificate)"]
    pub client_id: ::std::string::String,
    #[doc = "Client settings to update (only specified fields will be updated)"]
    #[serde(deserialize_with = "::std::option::Option::deserialize")]
    pub settings: ::std::option::Option<PartialClientSettings>,
}
#[doc = "`VideoSession`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct VideoSession {
    pub bitrate_kbps: i64,
    pub client_ip: ::std::string::String,
    pub color_range: VideoSessionColorRange,
    pub color_space: VideoSessionColorSpace,
    pub display_mode: DisplayMode,
    pub fec_percentage: i64,
    pub frames_with_invalid_ref_threshold: i64,
    pub gst_pipeline: ::std::string::String,
    pub min_required_fec_packets: i64,
    pub packet_size: i64,
    pub port: i64,
    pub render_node: ::std::string::String,
    pub rtp_secret_payload: [i64; 16usize],
    pub session_id: ::std::string::String,
    pub slices_per_frame: i64,
    pub timeout_ms: i64,
    pub wait_for_ping: bool,
}
#[doc = "`VideoSessionColorRange`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum VideoSessionColorRange {
    #[serde(rename = "JPEG")]
    Jpeg,
    #[serde(rename = "MPEG")]
    Mpeg,
}
impl ::std::fmt::Display for VideoSessionColorRange {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Jpeg => f.write_str("JPEG"),
            Self::Mpeg => f.write_str("MPEG"),
        }
    }
}
impl ::std::str::FromStr for VideoSessionColorRange {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "JPEG" => Ok(Self::Jpeg),
            "MPEG" => Ok(Self::Mpeg),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for VideoSessionColorRange {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for VideoSessionColorRange {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`VideoSessionColorSpace`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum VideoSessionColorSpace {
    #[serde(rename = "BT601")]
    Bt601,
    #[serde(rename = "BT709")]
    Bt709,
    #[serde(rename = "BT2020")]
    Bt2020,
}
impl ::std::fmt::Display for VideoSessionColorSpace {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Bt601 => f.write_str("BT601"),
            Self::Bt709 => f.write_str("BT709"),
            Self::Bt2020 => f.write_str("BT2020"),
        }
    }
}
impl ::std::str::FromStr for VideoSessionColorSpace {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "BT601" => Ok(Self::Bt601),
            "BT709" => Ok(Self::Bt709),
            "BT2020" => Ok(Self::Bt2020),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for VideoSessionColorSpace {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for VideoSessionColorSpace {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`VideoSettings`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct VideoSettings {
    pub height: i64,
    pub refresh_rate: i64,
    pub runner_render_node: ::std::string::String,
    pub video_producer_buffer_caps: ::std::string::String,
    pub wayland_render_node: ::std::string::String,
    pub width: i64,
}
#[doc = "`WolfApiTypes`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
#[serde(transparent)]
pub struct WolfApiTypes(pub ::serde_json::Map<::std::string::String, ::serde_json::Value>);
impl ::std::ops::Deref for WolfApiTypes {
    type Target = ::serde_json::Map<::std::string::String, ::serde_json::Value>;
    fn deref(&self) -> &::serde_json::Map<::std::string::String, ::serde_json::Value> {
        &self.0
    }
}
impl ::std::convert::From<WolfApiTypes>
    for ::serde_json::Map<::std::string::String, ::serde_json::Value>
{
    fn from(value: WolfApiTypes) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Map<::std::string::String, ::serde_json::Value>>
    for WolfApiTypes
{
    fn from(value: ::serde_json::Map<::std::string::String, ::serde_json::Value>) -> Self {
        Self(value)
    }
}
#[doc = " Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
