[package]
name = "wolf-ui"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
dioxus.workspace = true
dioxus-free-icons.workspace = true
wolf-api.workspace = true

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
